Fix a syntax error in the types definition file on TypeScript 3.9.3
This file was throwing a TypeScript syntax error when being required:

```
  ../../node_modules/@gadgetinc/react-hotkeys/index.d.ts(31,64): error TS1005: ';' expected.
```

This fixes it, types aren't like interfaces and can't have empty brackets.